name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  email_validator: ^3.0.0
  image_picker: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icons.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"                       
  image: "lib/assets/images/icons.png"     

  android_12:
    image: "lib/assets/images/icons.png"   
    icon_background_color: "#FFFFFF"

  ios: true
  android: true

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - .env

  fonts:
    - family: GreatVibes
      fonts:
        - asset: lib/fonts/GreatVibes-Regular.ttf

    - family: Amagro
      fonts:
        - asset: lib/fonts/Amagro.ttf

    - family: Alana
      fonts:
        - asset: lib/fonts/Alana_Pro_RUS.otf
